# Generated by Django 4.2.16 on 2024-12-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_order_orderauthor_orderbook_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='price',
        ),
    ]
